In [0]:
import gym
import numpy as np

from gym.envs.registration import register
register(
    id='Deterministic-4x4-FrozenLake-v0', #new environment
    entry_point='gym.envs.toy_text.frozen_lake:FrozenLakeEnv', 
    kwargs={'map_name': '4x4', 'is_slippery': False} # argument passed to the env
)
env = gym.make('Deterministic-4x4-FrozenLake-v0')
my_desk = [
    "GFFFF",
    "FFFFF",
    "FFFFG",
    "FFFFF",
    "FGFFG"
]
 


import gym

class CustomizedFrozenLake(gym.envs.toy_text.frozen_lake.FrozenLakeEnv):
    def __init__(self, **kwargs):
        super(CustomizedFrozenLake, self).__init__(**kwargs)

        for state in range(self.nS): # for all states
            for action in range(self.nA): # for all actions
                my_transitions = []
                for (prob, next_state, _, is_terminal) in self.P[state][action]:
                    row = next_state // self.ncol
                    col = next_state - row * self.ncol
                    tile_type = self.desc[row, col]
                    if tile_type == b'F':
                        reward = -1
                    elif tile_type == b'G':
                        reward = 10
                    #else:
                        #reward = 0

                    my_transitions.append((prob, next_state, reward, is_terminal))
                self.P[state][action] = my_transitions

from gym.envs.registration import register

register(
    id='Stochastic-5x5-FrozenLake-v0',
    entry_point='gym.envs.toy_text.frozen_lake:FrozenLakeEnv',
    kwargs={'desc': my_desk, 'is_slippery': False})
env = gym.make('Stochastic-5x5-FrozenLake-v0')
env.render()


GFFFF
FFFFF
FFFFG
FFFFF
FGFFG


/usr/local/lib/python3.6/dist-packages/gym/envs/toy_text/frozen_lake.py:112: RuntimeWarning: invalid value encountered in true_divide
  isd /= isd.sum()
/usr/local/lib/python3.6/dist-packages/gym/envs/toy_text/discrete.py:13: RuntimeWarning: invalid value encountered in greater
  return (csprob_n > np_random.rand()).argmax()


In [0]:
env.reset()
env.render()

print("Action Space {}".format(env.action_space))
print("State Space {}".format(env.observation_space))


GFFFF
FFFFF
FFFFG
FFFFF
FGFFG
Action Space Discrete(4)
State Space Discrete(25)


/usr/local/lib/python3.6/dist-packages/gym/envs/toy_text/discrete.py:13: RuntimeWarning: invalid value encountered in greater
  return (csprob_n > np_random.rand()).argmax()


In [0]:
"""ACTIONS DEFINED VIA:
    0 = SOUTH
    1 = NORTH
    2 = EAST
    3 = WEST
"""

state=env.s 
if state in range (0,14):
  print("State:", state)
elif state in range (14,20):
  print("State:", state+1)  
elif state in range (20,22):
  print("State:", state+2)

env.render()

State: 0

GFFFF
FFFFF
FFFFG
FFFFF
FGFFG


In [0]:
env.P[state][1]

[(1.0, 0, 0, True)]

In [0]:
m=int(input("Enter State numnber for start:"))

if m in range (0,14):
  env.s = m 
elif m in range (14,20):
  env.s = m+1
elif m in range (20,22):
  env.s = m+2
 # set environment to illustration's state
env.render()

print("....................Learning Starts........................")

epochs = 0
penalties, reward = 0, 0

frames = [] # for animation

done = False

while not done:
    action = env.action_space.sample()
    state, reward, done, info = env.step(action)

    if reward == -1:
        penalties += 1
    
    # Put each rendered frame into dict for animation
    frames.append({
        'frame' : env.render(mode='human'),
        'state': state,
        'action': action,
        'reward': reward
        }
    )

    epochs += 1
    
    
print("Timesteps taken: {}".format(epochs))
print("Penalties incurred: {}".format(penalties))
print("\n")
print(frames)



Enter State numnber for start:14

GFFFF
FFFFF
FFFFG
FFFFF
FGFFG
....................Learning Starts........................
  (Down)
GFFFF
FFFFF
FFFFG
FFFFF
FGFFG
  (Right)
GFFFF
FFFFF
FFFFG
FFFFF
FGFFG
Timesteps taken: 2
Penalties incurred: 0


[{'frame': None, 'state': 20, 'action': 1, 'reward': 0.0}, {'frame': None, 'state': 21, 'action': 2, 'reward': 1.0}]


In [0]:
from IPython.display import clear_output
from time import sleep

def print_frames(frames):
    for i, frame in enumerate(frames):
        clear_output(wait=True)
        print("frame: ",frame)
        print(f"Timestep: {i + 1}")
        #print(f"State: {frame['state']}")
        print(f"Action: {frame['action']}")
        print(f"Reward: {frame['reward']}")
        sleep(.1)
        
print_frames(frames)

frame:  {'frame': None, 'state': 24, 'action': 2, 'reward': 1.0}
Timestep: 1
Action: 2
Reward: 1.0


In [0]:
"""QLearning"""
import numpy as np
q_table = np.zeros([env.observation_space.n, env.action_space.n])
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
%%time
#Training the Agent

import random
from IPython.display import clear_output

# Hyperparameters
alpha = 0.1
gamma = 0.6
epsilon = 0.1

# For plotting metrics
all_epochs = []
all_penalties = []

for i in range(1, 10001):
    state = env.reset()

    epochs, penalties, reward, = 0, 0, 0
    done = False
    
    while not done:
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(q_table[state]) # Exploit learned values

        next_state, reward, done, info = env.step(action) 
        
        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value

        if reward == -1:
            penalties += 1

        state = next_state
        epochs += 1
        
    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")

print("Training finished.\n")

Episode: 100000
Training finished.

CPU times: user 7.5 s, sys: 2.33 s, total: 9.83 s
Wall time: 9.18 s


In [0]:
m=int(input(print("Enter state value:")))


for m in range (0,14):
  print(q_table[m])
for m in range (14,20):
  print(q_table[(m+1)])
for m in range (20,22):
  print(q_table[(m+2)])

Enter state value:
20
[0. 0. 0. 0.]
[1.   0.36 0.36 0.6 ]
[0.6        0.21599983 0.21599977 0.35999992]
[0.35999997 0.03954002 0.01053266 0.0582606 ]
[0.08836117 0.         0.         0.        ]
[0.59999976 0.35999989 0.35999997 1.        ]
[0.6        0.2159974  0.21599977 0.59999917]
[0.36       0.02348849 0.02607496 0.0684    ]
[0.16088968 0.         0.         0.        ]
[0. 0. 0. 0.]
[0.26911731 0.09340281 0.10309805 0.6       ]
[0.35999985 0.00175724 0.02009013 0.036     ]
[0.15117515 0.         0.         0.        ]
[0.00815816 0.         0.         0.        ]
[0.01549376 0.         0.         0.29322828]
[0.03047873 0.         0.         0.        ]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


'q_table[20]\n'

In [0]:
q_table[20] #Checking Qvalue for any random state

array([0., 0., 0., 0.])

In [0]:
"""Evaluating Agent's performance after Q-learning"""

total_epochs, total_penalties = 0, 0
episodes = 520148

for _ in range(episodes):
    state = env.reset()
    epochs, penalties, reward = 0, 0, 0
    
    done = False
    
    while not done:
        action = np.argmax(q_table[state])
        state, reward, done, info = env.step(action)

        if reward == -1:
            penalties += 1

        epochs += 1

    total_penalties += penalties
    total_epochs += epochs

print(f"Results after {episodes} episodes:")
print(f"Average timesteps per episode: {total_epochs / episodes}")
print(f"Average penalties per episode: {total_penalties / episodes}")

Results after 520148 episodes:
Average timesteps per episode: 1.0
Average penalties per episode: 0.0
